import { LegalPage, Section } from "@/components/legal-page";

export default function Privacy() {
  return (
    <LegalPage title="Privacy Policy" lastUpdated="June 2026">
      <Section title="Introduction">
        <p>
          Audistill is built on a simple principle: your data stays on your machine. We are a
          local-first macOS desktop application that processes audio entirely on-device. This Privacy
          Policy explains what data exists, where it lives, and the limited circumstances under which
          any data leaves your Mac.
        </p>
      </Section>

      <Section title="Data We Collect">
        <p>
          <strong className="text-text">Locally stored (never leaves your device):</strong>
        </p>
        <ul className="list-disc list-inside space-y-1.5 pl-1">
          <li>Audio files you import (stored in the app&apos;s support directory)</li>
          <li>Transcripts generated by on-device transcription</li>
          <li>Tabs, episodes, and library metadata</li>
          <li>Recipes (custom processing templates)</li>
          <li>Generated documents (summaries, show notes, etc.)</li>
          <li>Application settings and preferences</li>
        </ul>

        <p className="mt-4">
          <strong className="text-text">Cloud opt-in (only when you choose):</strong>
        </p>
        <ul className="list-disc list-inside space-y-1.5 pl-1">
          <li>
            Transcribed text sent to your chosen LLM provider (e.g., OpenRouter, Anthropic, OpenAI)
            for summaries, chat, and recipe execution — <em>only when you initiate an AI action</em>
          </li>
          <li>Your API key is used to authenticate directly with the provider — we never see or store it on our servers</li>
        </ul>

        <p className="mt-4">
          <strong className="text-text">What we never collect:</strong>
        </p>
        <ul className="list-disc list-inside space-y-1.5 pl-1">
          <li>Audio files are never transmitted anywhere — transcription runs entirely on-device via Parakeet TDT (ONNX)</li>
          <li>No telemetry, analytics, or usage tracking</li>
          <li>No crash reports sent without explicit consent</li>
          <li>No advertising identifiers or tracking pixels</li>
        </ul>
      </Section>

      <Section title="Data Storage">
        <p>All application data is stored locally on your Mac:</p>
        <ul className="list-disc list-inside space-y-1.5 pl-1">
          <li>
            <strong className="text-text">Database:</strong> SQLite database in the app&apos;s
            Application Support directory for transcripts, metadata, and library structure
          </li>
          <li>
            <strong className="text-text">API keys:</strong> Stored in the macOS Keychain, protected
            by your system&apos;s security (including Touch ID / password)
          </li>
          <li>
            <strong className="text-text">Audio files:</strong> Stored in the app&apos;s support
            directory on your local filesystem
          </li>
          <li>
            <strong className="text-text">Settings:</strong> Stored in the app&apos;s local preferences
          </li>
        </ul>
        <p>
          We operate no servers that store your data. There is no &ldquo;Audistill cloud.&rdquo;
        </p>
      </Section>

      <Section title="Data Retention">
        <p>
          You have full control over data retention. All data persists until you choose to delete it.
          There is no automatic deletion or expiration. You can:
        </p>
        <ul className="list-disc list-inside space-y-1.5 pl-1">
          <li>Delete individual episodes, transcripts, or generated documents at any time</li>
          <li>Remove your entire library</li>
          <li>Uninstall the app to remove all associated data</li>
        </ul>
      </Section>

      <Section title="Third-Party Services">
        <p>
          Audistill integrates with one category of third-party service: LLM providers for AI
          features.
        </p>
        <p className="mt-3">
          <strong className="text-text">OpenRouter / LLM Providers</strong>
        </p>
        <p>
          When you use AI features (summaries, chat, recipe execution), transcribed text is sent
          directly from your Mac to the LLM provider you configure. This connection is made using
          your own API key — Audistill acts as a client, not a proxy.
        </p>
        <ul className="list-disc list-inside space-y-1.5 pl-1 mt-2">
          <li>Only text is sent — never audio</li>
          <li>Requests go directly from your Mac to the provider&apos;s API</li>
          <li>We do not intercept, log, or store these requests</li>
          <li>
            Each provider has their own privacy policy (e.g.,{" "}
            <a
              href="https://openrouter.ai/privacy"
              target="_blank"
              rel="noopener noreferrer"
              className="text-accent hover:text-accent-hover underline underline-offset-2"
            >
              OpenRouter Privacy Policy
            </a>
            )
          </li>
        </ul>
        <p className="mt-3">
          If you do not configure an API key or do not use AI features, no data ever leaves your
          machine.
        </p>
      </Section>

      <Section title="Your Privacy Rights">
        <p>Because your data is stored locally, you have inherent control:</p>
        <ul className="list-disc list-inside space-y-1.5 pl-1">
          <li>
            <strong className="text-text">Access:</strong> All your data is in local files you can
            browse directly
          </li>
          <li>
            <strong className="text-text">Delete:</strong> Remove any or all data from within the app
            or by deleting files
          </li>
          <li>
            <strong className="text-text">Export:</strong> Your transcripts and documents are
            accessible as standard files
          </li>
          <li>
            <strong className="text-text">Edit:</strong> Modify any transcript or generated content
            directly
          </li>
          <li>
            <strong className="text-text">Opt-out of cloud:</strong> Simply don&apos;t add an API
            key — the app works for transcription without any cloud connection
          </li>
        </ul>
        <p>
          There is no account to delete and no server-side data to request removal of.
        </p>
      </Section>

      <Section title="Data Security">
        <p>
          Audistill relies on your Mac&apos;s built-in security mechanisms:
        </p>
        <ul className="list-disc list-inside space-y-1.5 pl-1">
          <li>API keys are stored in the macOS Keychain (hardware-backed encryption on Apple Silicon)</li>
          <li>Application data benefits from FileVault disk encryption if enabled</li>
          <li>The app is sandboxed and signed with Apple notarization</li>
          <li>No network connections are made except to LLM providers when you initiate AI actions</li>
        </ul>
      </Section>

      <Section title="Children's Privacy">
        <p>
          Audistill is not directed at children under the age of 13. We do not knowingly collect any
          personal information from children. Since the app stores all data locally and has no
          account system, there is no mechanism for us to identify or collect data from any user,
          including children.
        </p>
      </Section>

      <Section title="Changes to This Policy">
        <p>
          We may update this Privacy Policy from time to time. Changes will be reflected on this page
          with an updated &ldquo;Last updated&rdquo; date. Since Audistill is open source, you can
          also review changes in the project&apos;s commit history.
        </p>
      </Section>

      <Section title="Contact">
        <p>
          If you have questions about this Privacy Policy or Audistill&apos;s data practices, contact
          us at{" "}
          <a
            href="mailto:info@audistill.com"
            className="text-accent hover:text-accent-hover underline underline-offset-2"
          >
            info@audistill.com
          </a>
          .
        </p>
      </Section>
    </LegalPage>
  );
}
